# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Good Article 
email: jjvein@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  主要是自己看到的一些有趣的文章，还有一些是个人闲暇时间翻译的，若有侵权行为，请联系我。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jjvein
github_username:  jjvein


# Build settings
markdown: kramdown
